export const orderTypes = {
  ADD_ORDER: "ADD_ORDER",
  SUB_ORDER: "SUB_ORDER",
  CLEAR_ORDER: "CLEAR_ORDER",
  SET_TABLE: "SET_TABLE"
};
export const alertTypes = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
  CLEAR: "CLEAR"
}
export const userTypes = {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',
  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
  LOGOUT: 'USERS_LOGOUT'
}
export const tableTypes = {
  ACTION_SHOW_QR: 'ACTION_SHOW_QR',
  ACTION_SHOW_INVOICE: 'ACTION_SHOW_INVOICE',
  ACTION_SEND_INDEX: 'ACTION_SEND_INDEX',
  ACTION_CLOSE_QR: 'ACTION_CLOSE_QR',
  ACTION_CLOSE_INVOICE: 'ACTION_CLOSE_INVOICE',
  ACTION_LIST_TABLE: 'ACTION_LIST_TABLE',
  ACTION_CHANGE_TABLE_STATUS: 'ACTION_CHANGE_TABLE_STATUS',
  ACTION_SEND_TABLE: 'ACTION_SEND_TABLE'
}
