export const orderTypes = {
  ADD_ORDER: "ADD_ORDER",
  SUB_ORDER: "SUB_ORDER",
  CLEAR_ORDER: "CLEAR_ORDER",
  SET_TABLE: "SET_TABLE"
};
export const alertTypes = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
  CLEAR: "CLEAR"
}
export const userTypes = {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  LOGOUT: 'USERS_LOGOUT'
}
