export { default as Menu } from "./menu/Menu";
export { default as ViewOrder } from "./viewOrder/ViewOrder";
export { default as ForgotPW } from "./admin/users/ForgotPW/ForgotPW";
export { default as Login } from "./admin/users/login/Login";
export { default as Register } from "./admin/users/register/Register";
export { default as CreateProduct } from "./admin/product/createProduct/CreateProduct";
export { default as UpdateProduct } from "./admin/product/updateProduct/UpdateProduct";
export { default as ListProduct } from "./admin/product/listProduct/ListProduct";
export { default as ViewTable } from "./viewTable/ViewTable";